### ISSUE TITLE
Updated redirects

### ISSUE THREAD

**Issue by DamienIrving** [resbaz/resbaz2017#21]
@tjdett Just got the following feedback on Slack:
1. http://resbaz.com/ redirects to that broken URL
2. http://www.resbaz.com/ goes nowhere

Is it possible to have these point to https://2017.resbaz.com/?

**Comment by tjdett** [comment]
@DamienIrving I've updated https://resbaz.com/  to point to https://2017.resbaz.com/.

It's true that www.resbaz.com goes nowhere, however there shouldn't be any advertising materials anywhere that use that address.

**Comment by DamienIrving** [comment]
Thanks, @tjdett !

**Comment by DamienIrving** [comment]
@tjdett Would you mind responding to some of the questions about URL redirection at: https://resbaz-team.slack.com/messages/general/ ?

**Comment by tjdett** [comment]
As noted in chat, allowing `www.resbaz.com` would use up the last free page rule with Cloudflare, so until it's actually necessary I'm going to leave things as they are.

**Comment by andreabedini** [comment]
@DamienIrving @tjdett perhaps we can put this info into the repo `README.md`?
