### ISSUE TITLE
ResBaz domain broken

### ISSUE THREAD

**Issue by weaverbel** [resbaz/resbaz2017#25]
The ResBaz domain name has expired - can someone please get this sorted **ASAP**? All the sites are unreachable. @tjdett has been notified and may be on it, just FYI.

**Comment by andreabedini** [comment]
All fixed now

**Comment by weaverbel** [comment]
Not working again now @tjdett @andreabedini

**Comment by tjdett** [comment]
@weaverbel the DNS caching is likely to be a problem until later today for UQ, when the last of the long TTL records expire.

**Comment by andreabedini** [comment]
All fixed now :)
