### ISSUE TITLE
Linked code of conduct is Melbourne specific

### ISSUE THREAD

**Issue by andreabedini** [resbaz/resbaz2017#28]
Hi there,

there's a link at the bottom of every page linking to the code of conduct adopted by Melbourne. We're very happy with the code itself but the linked page is Melbourne specific ('please contact David Flanders')

http://melbourne.resbaz.edu.au/post/103597415589/research-bazaar-policies-and-code-of-conduct

How about we make a page on this website with the code of conduct? or even a template that can be customised per site (so 'please contact' can be customised).

**Comment by DamienIrving** [comment]
@andreabedini Good suggestion. Since we create a new website every year, I've added the code of conduct to the blog instead (i.e. as it won't change each year) and removed the Melbourne-specific information:
https://resbazblog.wordpress.com/code-of-conduct/

Does that seem like a good solution?

**Comment by andreabedini** [comment]
you're my hero @DamienIrving, do you want me to update the link at the footer?

**Comment by DamienIrving** [comment]
@andreabedini Already done :smile:

**Comment by andreabedini** [comment]
too much my hero :)

**Comment by weaverbel** [comment]
Loving the hero love @DamienIrving @andreabedini !
