### ISSUE TITLE
Cuenca Site

### ISSUE THREAD

**Issue by ivansanchezvera** [resbaz/resbaz2017#48]
I would like to add Cuenca-Ecuador as a Site for ResBaz 2017.

**Comment by ivansanchezvera** [comment]
=)

**Comment by DamienIrving** [comment]
@ivansanchezvera That would be great!

You can fork this repository and then follow the instructions in the "Contribution Guide" section of the [README](https://github.com/resbaz/resbaz2017/blob/gh-pages/README.md) file to create your page. Just let me know if you have any questions.

**Comment by ivansanchezvera** [comment]
Thanks we are all good now!
