### ISSUE TITLE
Site vanished

### ISSUE THREAD

**Issue by weaverbel** [resbaz/resbaz2017#49]
The Brisbane site has gone offline for some reason.  I can't see the issue with the file. Can anyone help?
When I try this address: https://2017.resbaz.com/brisbane/ I get a 404 File not Found.

HELP!!!!

**Comment by weaverbel** [comment]
And now it's working ! Sheesh, heart attack much????

**Comment by DamienIrving** [comment]
@weaverbel It looks like the following is valid:
https://2017.resbaz.com/brisbane

but not 
https://2017.resbaz.com/brisbane/

i.e. the trailing `/` is the problem. This is true for all the sites, not just Brisbane. 

cc'ing @tjdett and @andreabedini in case there is a super simple fix for this, but I suspect it's a little quirk we just have to live with.

**Comment by tjdett** [comment]
@damienirving @weaverbel it's likely fixable. You just need something to exist at `/brisbane/index.html` in addition to `/brisbane.html`. A symlink seems reasonable?
