### ISSUE TITLE
Create a Brisbane site

### ISSUE THREAD

**Issue by weaverbel** [resbaz/resbaz2017#5]
Hi there
Can a Brisbane base site be set up for me and @SamHames to work on, please?
Thanks
Belinda

**Comment by DamienIrving** [comment]
@weaverbel No problem. I've added a template Brisbane page and invited both you and @SamHames to be collaborators on this repo so you have write access.

**Comment by weaverbel** [comment]
Great, thanks @DamienIrving. We have decided on our dates so we will go ahead and start populating the site. We may be out of whack with others but we are running ours 7-8-9 February, 2017. @SamHames

**Comment by DamienIrving** [comment]
No problem if you're a little out of whack :smile:

**Comment by weaverbel** [comment]
We are go so am closing this.
