### ISSUE TITLE
Running bundle install gives error

### ISSUE THREAD

**Issue by apawlik** [resbaz/resbaz2017#8]
Your Gemfile.lock is corrupt. The following gems are missing from the DEPENDENCIES section: 'mini_portile2' 'pkg-config'

**Comment by andreabedini** [comment]
@apawlik is this still an issue for you? `mini_portile2` and `pkg-config` are included throughout the following list of dependencies `nokogiri -> html-pipeline -> jekyll-mentions -> github-pages`. So the should not be appear in `DEPENDENCIES`, only the top level ones (`github-pages` and `json_pure`) are there.

**Comment by andreabedini** [comment]
@apawlik feel free to reopen if it's still an issue
